### ISSUE TITLE
Make a client version with Angular 4

### ISSUE THREAD

**Issue by MattiaPrimavera** [cppccn/client#22]
https://angular.io/

**Comment by MattiaPrimavera** [comment]
Ehi mate, what do you think about this?
I've been reading the [Getting started for Angular 2](https://angular.io/docs/js/latest/quickstart.html) and it's true that everything changes ... tutorials are not even yet available for `javascript` since they're main intention I think is to use `TypeScript` ... 

It's true that Angular v1.0 it's like becoming deprecated let's say but it works and the job is kinda already done.

I think I would be fine in keeping on learning Angular v1.0 and using that for the moment.

**Comment by yvan-sraka** [comment]
`TypeScript` is so coooool :smile:!

**Comment by MattiaPrimavera** [comment]
Yeah I saw that, than I propose you we make both of them, I think the
client js code will be kept so little that we could just make a ticket on
this, and that would allow us to learn them both ;)

Angular v1.0 will probably still be used for a while probably since the
migration costs.

**Comment by MattiaPrimavera** [comment]
I mean, wouldn't both those technologies be valuable on our CVs?

**Comment by yvan-sraka** [comment]
_YES!_

**Comment by MattiaPrimavera** [comment]
I consequently updated the name of the ticket

**Comment by yvan-sraka** [comment]
I see that :smile:!

**Comment by yvan-sraka** [comment]
Ionic 3 is powered by Angular 4 and TypeScript, so https://github.com/cppccn/client/issues/25 solved this issue!
