### ISSUE TITLE
Refactor controller.js

### ISSUE THREAD

**Issue by MattiaPrimavera** [cppccn/client#37]
`controller.js` needs to be refactored:
- `sendCommandRequest` function should make calls to other functions to reflect the most possible a `modular structure` for commands logic
- [X] creation of `CommandsService` for handling commands
- [X] use of promises to retrieve $http response from `CommandsService` methods
- [ ] Encapsulate command logics inside `CommandService` = finish refactor

**Comment by MattiaPrimavera** [comment]
- [X] creation of `CommandsService` for handling commands
- [X] use of promises to retrieve $http response from `CommandsService` methods
- [ ] Encapsulate command logics inside `CommandService` = finish refactor

**Comment by yvan-sraka** [comment]
This is no longer accurate so I close it!
