### ISSUE TITLE
Node.js packages requirements

### ISSUE THREAD

**Issue by MattiaPrimavera** [cppccn/client#38]
It needs to be automatic when the user chooses to install the web server with the client module and not just as a REST API.

**Comment by MattiaPrimavera** [comment]
Let's say we both solved this since we worked on 'till night?
thanks to [Manuel Kiessling](http://manuel.kiessling.net/2014/06/09/creating-a-useful-angularjs-project-structure-and-toolchain/) for `package.json` and `bower.json` files

**Comment by yvan-sraka** [comment]
Now we have a standalone `package.json`!
