### ISSUE TITLE
make a nodejs server

### ISSUE THREAD

**Issue by MattiaPrimavera** [cppccn/client#41]

**Comment by MattiaPrimavera** [comment]
http://stackoverflow.com/questions/16333790/node-js-quick-file-server-static-files-over-http

**Comment by MattiaPrimavera** [comment]
http://stackoverflow.com/questions/2727167/how-do-you-get-a-list-of-the-names-of-all-files-present-in-a-directory-in-node-j

**Comment by MattiaPrimavera** [comment]
https://github.com/indexzero/http-server

**Comment by MattiaPrimavera** [comment]
https://developer.mozilla.org/en-US/docs/Node_server_without_framework

**Comment by yvan-sraka** [comment]
And of course now we also have a Node.js server!
